import { Link } from 'react-router-dom';
import { AlertCircle, ArrowLeft, Clock3, MapPin, Plus, ShieldCheck, Waves } from 'lucide-react';
import AppScreen from '@/components/layout/AppScreen';
import AtivoHomeCard from '@/components/product/AtivoHomeCard';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { ViewerCard, ViewerSection, ViewerSectionTitle, ViewerHorizontalScroller, ViewerActionBar, ViewerBadgeGroup, ViewerMetadataList, ViewerMetadataItem } from '@/components/viewer';
function formatLabel(v){if(!v)return'Nao informado';return String(v).replaceAll('_',' ')}
function formatCategoria(v){if(!v)return'Local';return v.charAt(0).toUpperCase()+v.slice(1)}
function LocalError({onRetry}){return(<AppScreen variant="warm"><div className="rounded-[var(--radius-card)] border border-error/20 bg-container-secondary p-5 shadow-card"><div className="mb-3 flex items-center gap-2 text-error"><AlertCircle className="h-5 w-5"/><h1 className="text-lg font-bold text-text-primary">Local nao encontrado</h1></div><p className="mb-4 text-sm leading-6 text-text-secondary">Nao conseguimos carregar este Local a partir dos dados oficiais.</p><div className="flex flex-col gap-2"><Button onClick={onRetry}>Tentar novamente</Button><Button asChild variant="outline"><Link to="/mapa">Voltar ao mapa</Link></Button></div></div></AppScreen>)}
function LocalHero({local}){return(<section className="overflow-hidden rounded-[var(--radius-card)] border border-borderSemantic-subtle bg-container-accent shadow-card"><div className="relative min-h-[190px] p-5"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(255,255,255,.35)_1px,transparent_1px),linear-gradient(0deg,rgba(255,255,255,.35)_1px,transparent_1px)] bg-[size:40px_40px]"/><div className="absolute right-5 top-5 flex h-16 w-16 items-center justify-center rounded-full bg-container-primary text-brand-primary shadow-sm"><Waves className="h-8 w-8"/></div><div className="relative max-w-[260px]"><Badge variant="secondary">{formatCategoria(local.categoria)}</Badge><h1 className="mt-4 text-3xl font-bold leading-9 text-text-primary">{local.nome}</h1><p className="mt-3 flex items-start gap-2 text-sm font-medium leading-5 text-text-secondary"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-text-tertiary"/><span>{[local.endereco,local.bairro,local.cidade].filter(Boolean).join(', ')}</span></p></div></div></section>)}
function LocalInfoCard({title,icon:Icon,items,emptyLabel}){return(<ViewerSection><ViewerSectionTitle icon={Icon}>{title}</ViewerSectionTitle>{items&&items.length>0?(<ViewerBadgeGroup>{items.map((i)=>(<Badge key={i}variant="secondary">{formatLabel(i)}</Badge>))}</ViewerBadgeGroup>):(<p className="text-sm text-text-tertiary">{emptyLabel}</p>)}</ViewerSection>)}
function LocalAtivosSection({local,ativos}){if(!ativos||ativos.length===0)return null;return(<ViewerSection><ViewerSectionTitle>Ativos neste Local</ViewerSectionTitle><div className="mb-3 flex items-center justify-between"><span/><Button asChild variant="link"className="text-sm"><Link to={'/mapa?localId='+local.id}>Ver no mapa</Link></Button></div><div className="flex flex-col gap-3">{ativos.map((a)=>(<AtivoHomeCard key={a.id}ativo={a}/>))}</div></ViewerSection>)}
function LocalNext24Hours(){return(<ViewerCard className="min-h-[100px]"><ViewerSectionTitle icon={Clock3}>Proximas 24 horas</ViewerSectionTitle><p className="mt-2 text-sm text-text-tertiary">Nenhum evento previsto para este periodo.</p></ViewerCard>)}
function LocalModalities(){return(<ViewerSection><ViewerSectionTitle>Modalidades</ViewerSectionTitle><ViewerHorizontalScroller><div className="flex h-20 w-32 items-center justify-center rounded-[var(--radius-card)] bg-container-accent text-sm font-medium text-text-secondary">Modalidade</div><div className="flex h-20 w-32 items-center justify-center rounded-[var(--radius-card)] bg-container-accent text-sm font-medium text-text-secondary">Modalidade</div><div className="flex h-20 w-32 items-center justify-center rounded-[var(--radius-card)] bg-container-accent text-sm font-medium text-text-secondary">Modalidade</div></ViewerHorizontalScroller></ViewerSection>)}
function LocalInformation({local}){return(<ViewerSection><ViewerSectionTitle icon={ShieldCheck}>Informacoes</ViewerSectionTitle>{local.descricao&&(<p className="mb-4 text-sm leading-6 text-text-secondary">{local.descricao}</p>)}<ViewerMetadataList><ViewerMetadataItem label="Endereco"value={local.endereco??'Nao informado'}/><ViewerMetadataItem label="Bairro"value={local.bairro??'Nao informado'}/><ViewerMetadataItem label="Cidade"value={local.cidade??'Nao informado'}/></ViewerMetadataList></ViewerSection>)}
function LocalActions({local}){return(<ViewerCard className="bg-surface-inverse text-text-inverse"><ViewerActionBar><Button asChild className="w-full"variant="secondary"><Link to={'/ativos/novo?localId='+local.id}><Plus className="h-4 w-4"/>Criar Ativo</Link></Button><Button asChild className="w-full"variant="secondary"><Link to={'/zeladoria/nova?localId='+local.id}><Plus className="h-4 w-4"/>Abrir Zeladoria</Link></Button></ViewerActionBar></ViewerCard>)}
export default function LocalViewer({local,ativos,onRetry}){if(!local)return<LocalError onRetry={onRetry}/>;return(<AppScreen className="gap-5"variant="warm"><Button asChild variant="link"className="w-fit text-sm font-bold"><Link to="/mapa"><ArrowLeft className="h-4 w-4"/>Voltar ao mapa</Link></Button><LocalHero local={local}/><LocalNext24Hours/><LocalModalities/><LocalInformation local={local}/><div className="grid gap-3"><LocalInfoCard title="Estrutura"icon={MapPin}items={local.estrutura}emptyLabel="Estrutura ainda nao informada para este Local."/><LocalInfoCard title="Acessibilidade"icon={ShieldCheck}items={local.acessibilidade}emptyLabel="Acessibilidade ainda nao informada para este Local."/></div><LocalActions local={local}/><LocalAtivosSection local={local}ativos={ativos}/></AppScreen>)}
